# Generated by Django 3.1.2 on 2021-03-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('branch', models.CharField(max_length=100)),
                ('complaint_regarding', models.CharField(max_length=200)),
                ('complaint_message', models.TextField(max_length=1000)),
                ('status', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
