# Generated by Django 3.1.2 on 2021-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20210311_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_regarding',
            field=models.CharField(choices=[('admission', 'Admission'), ('finance', 'Finance'), ('exam', 'Examination'), ('learning', 'Learning')], default='admission', max_length=30),
        ),
    ]
