# Generated by Django 3.1.2 on 2021-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20210311_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('mec', 'MEC'), ('eee', 'EEE'), ('civ', 'CIV'), ('auto', 'AUTO')], default='cse', max_length=100),
        ),
    ]
