# Generated by Django 3.1.2 on 2021-03-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20210311_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('EEE', 'EEE'), ('CIV', 'CIV'), ('AUTO', 'AUTO')], default='cse', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_regarding',
            field=models.CharField(choices=[('Admission', 'Admission'), ('Finance', 'Finance'), ('Examination', 'Examination'), ('Learning', 'Learning')], default='admission', max_length=30),
        ),
    ]
