# Generated by Django 3.1.2 on 2021-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('EEE', 'EEE'), ('CIV', 'CIV'), ('AUTO', 'AUTO')], default='cse', max_length=30),
        ),
    ]
